version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: university
      MYSQL_USER: admin
      MYSQL_PASSWORD: root123
      MYSQL_ALLOW_EMPTY_PASSWORD: "false" 
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: